WIP
Now at `aws_codepipeline.foo: [ERROR] Error creating CodePipeline:
InvalidActionDeclarationException: Action Source declares 0 output
artifacts which is less than the minimum count (1)`